# Schema for the configuration files of the Toolbar module.

toolbar.settings:
  type: config_object
  label: 'Toolbar settings'
  mapping:
    admin_tray:
      type: mapping
      label: 'Admin tray settings'
      mapping:
        menu_name:
          type: string
          label: 'Menu to use in the toolbar admin tray'
