name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2020-10-22
version: '9.2.x-dev'
project: 'drupal'
datestamp: 1603367008
