name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
hidden: true
install:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2020-10-22
version: '9.2.x-dev'
project: 'drupal'
datestamp: 1603367007
